module.exports = [
    {name:"Please select a city"},
    {name:"Bath"},
    {name:"Birmingham"},
    {name:"Bradford"},
    {name:"Brighton & Hove"},
    {name:"Bristol"},
    {name:"Cambridge"},
    {name:"Canterbury"},
    {name:"Carlisle"},
    {name:"Chelmsford"},
    {name:"Chester"},
    {name:"Chichester"},
    {name:"Coventry"},
    {name:"Derby"},
    {name:"Durham"},
    {name:"Ely"},
    {name:"Exeter"},
    {name:"Gloucester"},
    {name:"Hereford"},
    {name:"Kingston upon Hull"},
    {name:"Lancaster"},
    {name:"Leeds"},
    {name:"Leicester"},
    {name:"Lichfield"},
    {name:"Lincoln"},
    {name:"Liverpool"},
    {name:"London"},
    {name:"Manchester"},
    {name:"Newcastle upon Tyne"},
    {name:"Norwich"},
    {name:"Nottingham"},
    {name:"Oxford"},
    {name:"Peterborough"},
    {name:"Plymouth"},
    {name:"Portsmouth"},
    {name:"Preston"},
    {name:"Ripon"},
    {name:"Ripon"},
    {name:"Salford"},
    {name:"Salisbury"},
    {name:"Sheffield"},
    {name:"Southampton"},
    {name:"St Albans"},
    {name:"Stoke-on-Trent"},
    {name:"Sunderland"},
    {name:"Truro"},
    {name:"Wakefield"},
    {name:"Wells"},
    {name:"Westminster"},
    {name:"Winchester"},
    {name:"Wolverhampton"},
    {name:"Worcester"},
    {name:"York"},
    {name:"Armagh"},
    {name:"Belfast"},
    {name:"Londonderry"},
    {name:"Lisburn"},
    {name:"Newry"},
    {name:"Aberdeen"},
    {name:"Dundee"},
    {name:"Edinburgh"},
    {name:"Glasgow"},
    {name:"Inverness"},
    {name:"Perth"},
    {name:"Stirling"},
    {name:"Bangor"},
    {name:"Cardiff"},
    {name:"Newport"},
    {name:"St. Asaph"},
    {name:"St. David's"},
    {name:"Swansea"}
  ]
